# Generated by Django 6.0 on 2026-01-04 11:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='gateway_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_select_assets', models.BooleanField(default=False)),
                ('website_url', models.URLField(unique=True)),
                ('support_email', models.EmailField(max_length=254)),
                ('support_link', models.URLField(validators=[django.core.validators.RegexValidator(message='Enter a valid URL.', regex='^(?:https?://)?(?:www\\.)?[A-Za-z0-9.-]+\\.[A-Za-z]{2,}(?:/(?:[^/\\s]+(?:/[^/\\s]*)*))?$')])),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_fee_payer', models.CharField(choices=[('merchant', 'Merchant'), ('user', 'User')], default='merchant', max_length=10)),
                ('commission_fee_payer', models.CharField(choices=[('merchant', 'Merchant'), ('user', 'User')], default='merchant', max_length=10)),
                ('cover_type', models.CharField(choices=[('usd', 'USD'), ('percentage', 'Percentage')], default='usd', max_length=10)),
                ('cover_range_up', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cover_range_down', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('assets', models.ManyToManyField(blank=True, related_name='gateways', to='assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
