# Generated by Django 6.0 on 2026-01-04 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='network',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='price_usd',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='transaction_fee',
        ),
        migrations.CreateModel(
            name='AssetNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('transaction_fee', models.DecimalField(decimal_places=4, max_digits=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_networks', to='assets.asset')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_assets', to='assets.network')),
            ],
            options={
                'unique_together': {('asset', 'network')},
            },
        ),
    ]
