# Generated by Django 6.0 on 2026-01-05 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_remove_asset_network_remove_asset_price_usd_and_more'),
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paylink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('telegram_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('is_amount_user_selectable', models.BooleanField(default=False)),
                ('limited_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('transaction_fee_payer', models.CharField(choices=[('merchant', 'Merchant'), ('user', 'User')], default='merchant', max_length=10)),
                ('transaction_commission_fee_payer', models.CharField(choices=[('merchant', 'Merchant'), ('user', 'User')], default='merchant', max_length=10)),
                ('cover_type', models.CharField(choices=[('usd', 'USD'), ('percentage', 'Percentage')], default='usd', max_length=10)),
                ('cover_range_up', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cover_range_down', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_on', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AED', 'United Arab Emirates Dirham'), ('IRT', 'Iranian Rial'), ('TRY', 'Turkish Lira')], default='USD', max_length=3)),
                ('assets', models.ManyToManyField(related_name='paylinks', to='assets.asset')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paylinks', to='gateway.gateway')),
            ],
        ),
    ]
