# Generated by Django 6.0 on 2026-01-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paylink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylink',
            name='cover_range_down',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paylink',
            name='cover_range_up',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paylink',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
