# Generated by Django 6.0 on 2026-01-05 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_remove_asset_network_remove_asset_price_usd_and_more'),
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in progress', 'In Progress'), ('success', 'Success'), ('expired', 'Expired'), ('acceptable', 'Acceptable'), ('mismatch', 'Mismatch')], default='in progress', max_length=20)),
                ('payment_UID', models.CharField(max_length=100, unique=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('type', models.CharField(choices=[('direct', 'Direct'), ('paylink', 'Paylink')], default='direct', max_length=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='assets.asset')),
                ('asset_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='assets.assetnetwork')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='gateway.gateway')),
            ],
        ),
    ]
