# Generated by Django 6.0 on 2026-01-05 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paylink', '0002_alter_paylink_cover_range_down_and_more'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paylink',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='paylink.paylink'),
            preserve_default=False,
        ),
    ]
