# Generated by Django 6.0 on 2026-01-05 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paylink', '0002_alter_paylink_cover_range_down_and_more'),
        ('transaction', '0002_transaction_paylink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paylink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='paylink.paylink'),
        ),
    ]
