# Generated by Django 6.0 on 2026-01-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_paylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
