# Generated by Django 6.0 on 2026-01-05 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_remove_asset_network_remove_asset_price_usd_and_more'),
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='gateway.gateway')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='assets.network')),
            ],
            options={
                'unique_together': {('gateway', 'network', 'address')},
            },
        ),
    ]
